#ifndef RUS_INGAME_MENU_ANSI_TO_CREDITS_CHAR_H
#define RUS_INGAME_MENU_ANSI_TO_CREDITS_CHAR_H

#include <rus/windows_1251_charmap.h>

if (c == ANSI_CHAR_CYRILLIC_CAPITAL_A || c == ANSI_CHAR_CYRILLIC_SMALL_A) {
    return ASCII_TO_DIALOG('A');
}
if (c == ANSI_CHAR_CYRILLIC_CAPITAL_BE || c == ANSI_CHAR_CYRILLIC_SMALL_BE) {
    return CREDITS_CHAR_CYRILLIC_BE;
}
if (c == ANSI_CHAR_CYRILLIC_CAPITAL_VE || c == ANSI_CHAR_CYRILLIC_SMALL_VE) {
    return ASCII_TO_DIALOG('B');
}
if (c >= ANSI_CHAR_CYRILLIC_CAPITAL_GHE && c <= ANSI_CHAR_CYRILLIC_CAPITAL_DE) {
    return (c - SUB_CREDITS_CHAR_CYRILLIC - 1);
}
if (c >= ANSI_CHAR_CYRILLIC_SMALL_GHE && c <= ANSI_CHAR_CYRILLIC_SMALL_DE) {
    return (c - SUB_CREDITS_CHAR_CYRILLIC - 1 - SUB_ANSI_LC_TO_UC);
}
if (c == ANSI_CHAR_CYRILLIC_CAPITAL_IE || c == ANSI_CHAR_CYRILLIC_SMALL_IE) {
    return ASCII_TO_DIALOG('E');
}
if (c >= ANSI_CHAR_CYRILLIC_CAPITAL_ZHE && c <= ANSI_CHAR_CYRILLIC_CAPITAL_I_SHORT) {
    return (c - SUB_CREDITS_CHAR_CYRILLIC - 2);
}
if (c >= ANSI_CHAR_CYRILLIC_SMALL_ZHE && c <= ANSI_CHAR_CYRILLIC_SMALL_I_SHORT) {
    return (c - SUB_CREDITS_CHAR_CYRILLIC - 2 - SUB_ANSI_LC_TO_UC);
}
if (c == ANSI_CHAR_CYRILLIC_CAPITAL_KA || c == ANSI_CHAR_CYRILLIC_SMALL_KA) {
    return ASCII_TO_DIALOG('K');
}
if (c == ANSI_CHAR_CYRILLIC_CAPITAL_EL || c == ANSI_CHAR_CYRILLIC_SMALL_EL) {
    return CREDITS_CHAR_CYRILLIC_EL;
}
if (c == ANSI_CHAR_CYRILLIC_CAPITAL_EM || c == ANSI_CHAR_CYRILLIC_SMALL_EM) {
    return ASCII_TO_DIALOG('M');
}
if (c == ANSI_CHAR_CYRILLIC_CAPITAL_EN || c == ANSI_CHAR_CYRILLIC_SMALL_EN) {
    return ASCII_TO_DIALOG('H');
}
if (c == ANSI_CHAR_CYRILLIC_CAPITAL_O || c == ANSI_CHAR_CYRILLIC_SMALL_O) {
    return ASCII_TO_DIALOG('O');
}
if (c == ANSI_CHAR_CYRILLIC_CAPITAL_PE || c == ANSI_CHAR_CYRILLIC_SMALL_PE) {
    return CREDITS_CHAR_CYRILLIC_PE;
}
if (c == ANSI_CHAR_CYRILLIC_CAPITAL_ER || c == ANSI_CHAR_CYRILLIC_SMALL_ER) {
    return ASCII_TO_DIALOG('P');
}
if (c == ANSI_CHAR_CYRILLIC_CAPITAL_ES || c == ANSI_CHAR_CYRILLIC_SMALL_ES) {
    return ASCII_TO_DIALOG('C');
}
if (c == ANSI_CHAR_CYRILLIC_CAPITAL_TE || c == ANSI_CHAR_CYRILLIC_SMALL_TE) {
    return ASCII_TO_DIALOG('T');
}
if (c >= ANSI_CHAR_CYRILLIC_CAPITAL_U && c <= ANSI_CHAR_CYRILLIC_CAPITAL_EF) {
    return (c - SUB_CREDITS_CHAR_CYRILLIC - 9);
}
if (c >= ANSI_CHAR_CYRILLIC_SMALL_U && c <= ANSI_CHAR_CYRILLIC_SMALL_EF) {
    return (c - SUB_CREDITS_CHAR_CYRILLIC - 9 - SUB_ANSI_LC_TO_UC);
}
if (c == ANSI_CHAR_CYRILLIC_CAPITAL_HA || c == ANSI_CHAR_CYRILLIC_SMALL_HA) {
    return ASCII_TO_DIALOG('X');
}
if (c >= ANSI_CHAR_CYRILLIC_CAPITAL_TSE && c <= ANSI_CHAR_CYRILLIC_CAPITAL_YA) {
    return (c - SUB_CREDITS_CHAR_CYRILLIC - 10);
}
if (c >= ANSI_CHAR_CYRILLIC_SMALL_TSE) {
    return (c - SUB_CREDITS_CHAR_CYRILLIC - 10 - SUB_ANSI_LC_TO_UC);
}
if (c == ANSI_CHAR_CYRILLIC_CAPITAL_IO || c == ANSI_CHAR_CYRILLIC_SMALL_IO) {
    return CREDITS_CHAR_CYRILLIC_IO;
}

#endif // This will be used in "src/game/ingame_menu.c"
