#ifndef RUS_DEFINES_HUD_TEXT_X_H
#define RUS_DEFINES_HUD_TEXT_X_H

#include "config.h"

#define TXT_TIME_X        158
#define TXT_TIME_X_OFFSET 7
#define TXT_TIME_X_OUTPUT \
( \
	(GFX_DIMENSIONS_FULL_RADIUS <= SCREEN_WIDTH) ? \
		GFX_DIMENSIONS_RECT_FROM_RIGHT_EDGE(SCREEN_WIDTH - TXT_TIME_X - TXT_TIME_X_OFFSET) \
	: (GFX_DIMENSIONS_FULL_RADIUS >= (SCREEN_WIDTH + (TXT_TIME_X_OFFSET * 3))) ? \
		GFX_DIMENSIONS_RECT_FROM_RIGHT_EDGE(SCREEN_WIDTH - TXT_TIME_X) \
	: \
		(f32)(TXT_TIME_X + TXT_TIME_X_OFFSET + ((GFX_DIMENSIONS_FULL_RADIUS - SCREEN_WIDTH) / 4)) \
)

#define TXT_HISCORE_X  119
#define TXT_CONGRATS_X 94

#endif
