#ifndef RUS_DEFINES_TEXT_STRINGS_WIN1251_H
#define RUS_DEFINES_TEXT_STRINGS_WIN1251_H

#define TXT_HUD_NO_CONTROLLER "мер йнмрпнккепю"
#define TXT_HUD_PRESS         "мюфлх"
#define TXT_HUD_START         "START"
#define TXT_HUD_TIME          "бпелъ"

#define NAME_S_MIYAMOTO  "яхцщпс лхълнрн"
#define NAME_Y_KOIZUMI   "╗яхюйх йнхдгслх"
#define NAME_T_TEZUKA    "рюйюях рщдгсйю"
#define NAME_Y_NISHIDA   "ъясмюпх мхяхдю"
#define NAME_Y_TANIMOTO  "╗яхмнпх рюмхлнрн"
#define NAME_H_YAJIMA    "уюдгхле ъдгхлю"
#define NAME_D_IWAMOTO   "дюийх хбюлнрн"
#define NAME_T_IWAWAKI   "рняхн хбюбюйх"
#define NAME_T_KAWAGOE   "рюйслх йюбюцнщ"
#define NAME_G_GODDARD   "дфюикя цнддюпд"
#define NAME_Y_YAMADA    "╗хрх ълюдю"
#define NAME_Y_YAMAMURA  "ъясухяю ълюлспю"
#define NAME_K_USUI      "йщмрю сясх"
#define NAME_N_MORI      "мюнйх лнпх"
#define NAME_Y_HARUHANA  "╗яхйх уюпсуюмю"
#define NAME_M_MIYANAGA  "люйнрн лхъмюцю"
#define NAME_K_KANNO     "йюжсухйн йюммн"
#define NAME_K_KONDO     "йндгх йнмдн"
#define NAME_Y_INAGAKI   "╗дгх хмюцюйх"
#define NAME_H_SHIMIZU   "ухдщюйх яхлхдгс"
#define NAME_S_TAKIZAWA  "яюрнпс рюйхдгюбю"
#define NAME_M_ARIMOTO   "люяюмюн юпхлнрн"
#define NAME_T_SAWANO    "рюйюн яюбюмн"
#define NAME_H_YOSHIMOTO "ухпнухрн ╗яхлнрн"
#define NAME_H_YADA      "ухпнрн ъдю"
#define NAME_K_FUKUI     "йхлх╗ях тсйсх"
#define NAME_K_KATO      "йеидгн йюрн"
#define NAME_C_MARTINET  "вюпкэг люпрхме"
#define NAME_L_SWAN      "кеякх ябюм"
#define NAME_H_YAMAUCHI  "ухпнях ълюсрх"

#define TITLE_GAME_DIRECTOR         "дхпейрнп хцпш"
#define TITLE_ASSISTANT_DIRECTORS   "дхпейрнпш юяяхяремрю"
#define TITLE_SYSTEM_PROGRAMMERS    "яхярелмше опнцпюллхярш"
#define TITLE_PROGRAMMERS           "опнцпюллхярш"
#define TITLE_CAMERA_PROGRAMMER     "опнцпюллхяр йюлепш"
#define TITLE_MARIO_FACE_PROGRAMMER "опнцпюллхяр кхжю люпхн"
#define TITLE_COURSE_DIRECTORS      "дхпейрнпш йспяю"
#define TITLE_COURSE_DESIGNERS      "дхгюимепш йспяю"
#define TITLE_SOUND_COMPOSER        "йнлонгхрнп"
#define TITLE_SOUND_EFFECTS         "гбсйнбше щттейрш"
#define TITLE_SOUND_PROGRAMMER      "опнцпюллхяр гбсйю"
#define TITLE_3D_ANIMATORS          "3 D юмхлюрнпш"
#define TITLE_ADDITIONAL_GRAPHICS   "днонкмхрекэмюъ цпютхйю"
#define TITLE_TECHNICAL_SUPPORT     "реуонддепфйю"
#define TITLE_PROGRESS_MANAGEMENT   "лемедфелемр опнцпеяяю"
#define TITLE_MARIO_VOICE           "цнкня люпхн"
#define TITLE_PEACH_VOICE           "цнкня охв"
#define TITLE_SPECIAL_THANKS_TO     "нянаюъ акюцндюпмнярэ"
#define TITLE_PRODUCER              "опндчяеп"
#define TITLE_EXECUTIVE_PRODUCER    "хяонкмхрекэмши опндчяеп"

#define NAME_SGI_N64_PROJECT_STAFF  "SGI N64 PROJECT STAFF"
#define NAME_EAD_STAFF              "EAD STAFF"
#define NAME_ALL_NINTENDO_PERSONNEL "ALL NINTENDO PERSONNEL"
#define NAME_MARIO_CLUB_STAFF       "MARIO CLUB STAFF"

#define YOURTEXT_1                  "псяхтхйюрнп х оепебнд"
#define YOURTEXT_2                  "ALEXN"

#endif
