#ifndef RUS_CONST_CREDITS_LUT_H
#define RUS_CONST_CREDITS_LUT_H

texture_credits_char_cyrillic_be,    texture_credits_char_cyrillic_ghe,
texture_credits_char_cyrillic_de,    texture_credits_char_cyrillic_zhe,
texture_credits_char_cyrillic_ze,    texture_credits_char_cyrillic_i,
texture_credits_char_accent_breve,   texture_credits_char_cyrillic_el,
texture_credits_char_cyrillic_pe,    texture_credits_char_cyrillic_u,
texture_credits_char_cyrillic_ef,    texture_credits_char_cyrillic_tse,
texture_credits_char_cyrillic_che,   texture_credits_char_cyrillic_sha,
texture_credits_char_cyrillic_shcha, texture_credits_char_cyrillic_hard_sign,
texture_credits_char_cyrillic_yeru,  texture_credits_char_cyrillic_soft_sign,
texture_credits_char_cyrillic_e,     texture_credits_char_cyrillic_yu,
texture_credits_char_cyrillic_ya,    texture_credits_char_accent_diaeresis,
texture_credits_char_undersym_left,  texture_credits_char_undersym_right,

#endif // This will be used in "bin/segment2.c"
