#ifndef RUS_DEFINE_HUD_TEXT_TIME_X_H
#define RUS_DEFINE_HUD_TEXT_TIME_X_H

#include "config.h"

#define TXT_TIME_X_OUTPUT \
((GFX_DIMENSIONS_FULL_RADIUS <= (SCREEN_WIDTH + TXT_TIME_X_OFFSET)) ? TXT_TIME_X : \
 (GFX_DIMENSIONS_FULL_RADIUS >= (SCREEN_WIDTH + (TXT_TIME_X_OFFSET * 3))) ? (TXT_TIME_X + TXT_TIME_X_OFFSET) : \
 (TXT_TIME_X + ((GFX_DIMENSIONS_FULL_RADIUS - SCREEN_WIDTH - TXT_TIME_X_OFFSET) / 2)))

#endif
