#ifndef RUS_DEFINE_HUD_TEXT_TIME_X_H
#define RUS_DEFINE_HUD_TEXT_TIME_X_H

#include "config.h"

f32 TXT_TIME_X_OUTPUT;

if (GFX_DIMENSIONS_FULL_RADIUS <= (SCREEN_WIDTH + TXT_TIME_X_OFFSET)) {
	TXT_TIME_X_OUTPUT = TXT_TIME_X;
} else if (GFX_DIMENSIONS_FULL_RADIUS >= (SCREEN_WIDTH + (TXT_TIME_X_OFFSET * 3))) {
	TXT_TIME_X_OUTPUT = (TXT_TIME_X + TXT_TIME_X_OFFSET);
} else {
	TXT_TIME_X_OUTPUT = (TXT_TIME_X + ((GFX_DIMENSIONS_FULL_RADIUS - SCREEN_WIDTH - TXT_TIME_X_OFFSET) / 2));
}

#endif
